name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-functions:
    name: deploy Firebase Functions
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: functions/package-lock.json
      - name: Install dependencies
        run: npm install -C functions

      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          service_account: github-actions@ankoromochi-6482c.iam.gserviceaccount.com
          workload_identity_provider: projects/1086517124040/locations/global/workloadIdentityPools/github-actions-pool1/providers/github-actions-provider

      - name: Install firebase tools
        run: npm install -g firebase-tools

      - name: Deploy
        run: firebase deploy --only functions

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ steps.auth.outputs.credentials_file_path }}
